export const CITIES = [
  ['Dubai', 'city-dubai'],
  ['Abu Dhabi', 'city-abudhabi'],
  ['New York', 'city-newyork'],
  ['London', 'city-london'],
  ['Sydney', 'city-sydney'],
  ['Mumbai', 'city-mumbai'],
  ['Riyadh', 'city-riyadh'],
  ['Johannesburg', 'city-johannesburg'],
] as const;

export const SOL_MAP: Record<string, string> = {
  'sol-seo': 'seo',
  'sol-localseo': 'local-seo',
  'sol-ads': 'lead-gen',
  'sol-linkedin': 'social-media',
  'sol-consulting': 'consultation',
  'sol-social': 'social-media',
  'sol-leadgen': 'lead-gen',
  'sol-web': 'web-dev',
};

export const CITY_DATA = {
  dubai: {
    name: "Dubai",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    tagline: "The Digital Capital of the Middle East.",
    sub: "We help Dubai-based brands and global businesses targeting the UAE market build digital authority, generate qualified leads, and outrank competitors on Google.ae.",
    badge: "UAE",
    stats: [["99%", "Internet Penetration"], ["73%", "Mobile Search Share"], ["97.5%", "Google Market Share"], ["5.5M+", "LinkedIn UAE Users"]],
    services: [
      ["SEO Agency Dubai", "Rank #1 on Google.ae for high-intent keywords in English and Arabic.", "sol-seo"],
      ["Local SEO Dubai", "Own Google Maps and near-me searches across all Emirates.", "sol-localseo"],
      ["Google Ads Dubai", "UAE-specific audience targeting and daily ROAS reporting.", "sol-ads"],
      ["LinkedIn Marketing UAE", "Reach Dubai's decision-maker community at scale.", "sol-linkedin"],
    ],
    why: "Dubai is one of the most competitive digital markets in the world. With a tech-savvy, multilingual population and among the highest mobile internet usage globally, generic marketing simply doesn't work here. You need a partner who understands the UAE buyer psychology, Arabic-English bilingual SEO, and the local regulatory landscape.",
    market: ["Bilingual SEO (Arabic + English)", "UAE consumer purchasing habits", "MENA social media trends", "Google.ae algorithm nuances", "Expo 2020 legacy economic landscape"],
    industries: ["Real Estate", "Hospitality & Tourism", "Healthcare & Medical", "Finance & Fintech", "Luxury Retail", "F&B & Restaurants"],
  },
  abudhabi: {
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    tagline: "The Capital. The Market. The Opportunity.",
    sub: "Abu Dhabi is the seat of government and home to sovereign wealth, enterprise sectors, and a growing SME ecosystem. We help brands capture high-value buyers in the capital.",
    badge: "UAE",
    stats: [["1.5M+", "Population"], ["98%", "Internet Usage"], ["#1", "MENA Quality of Life"], ["$500B+", "GDP (UAE)"]],
    services: [
      ["SEO Agency Abu Dhabi", "First-page Google dominance for Abu Dhabi search queries.", "sol-seo"],
      ["Government & Enterprise Marketing", "Reaching decision-makers in Abu Dhabi's institutional sectors.", "sol-consulting"],
      ["Google Ads Abu Dhabi", "Locally targeted paid campaigns with verified ROAS.", "sol-ads"],
      ["Social Media Marketing UAE", "Platform strategy for Abu Dhabi's discerning audience.", "sol-social"],
    ],
    why: "Abu Dhabi's economy is anchored by government, energy, and hospitality — sectors that demand credibility and precision. Our strategies are built for long buyer cycles, institutional trust-building, and B2B lead generation in the UAE's capital market.",
    market: ["Government & institutional procurement cycles", "Enterprise B2B buyer journeys", "Abu Dhabi ADGM financial sector", "Arabic-first content requirements", "High-spend luxury consumer segments"],
    industries: ["Government & Public Sector", "Energy & Petroleum", "Healthcare", "Finance & Wealth Management", "Hospitality", "Real Estate"],
  },
  newyork: {
    name: "New York",
    country: "United States",
    flag: "🇺🇸",
    tagline: "The Most Competitive Market in the World.",
    sub: "New York demands elite SEO, sophisticated paid media, and a brand presence that cuts through the noise. We've helped brands win in Manhattan and beyond.",
    badge: "NYC",
    stats: [["8.3M+", "Population NYC"], ["$2T+", "Metro Area GDP"], ["92%", "Internet Penetration"], ["Top 5", "Global Ad Market"]],
    services: [
      ["SEO Agency New York", "Outrank New York competitors in the toughest search landscape.", "sol-seo"],
      ["Performance Marketing NYC", "Google and Meta campaigns optimized for New York CPL benchmarks.", "sol-ads"],
      ["Lead Generation New York", "B2B and B2C pipelines built for New York's competitive environment.", "sol-leadgen"],
      ["Content Strategy NYC", "Authority content that resonates with discerning American buyers.", "sol-consulting"],
    ],
    why: "New York is where the best compete. Whether you're targeting Wall Street decision-makers, Brooklyn consumers, or SaaS buyers across the Northeast, we build the strategies that get you seen — and remembered — in the USA's most competitive market.",
    market: ["US consumer behavior & FTC compliance", "Competitive NYC keyword landscapes", "American e-commerce buyer psychology", "B2B enterprise sales cycles in the US", "East Coast media & PR dynamics"],
    industries: ["Finance & Wall Street", "Real Estate & PropTech", "Fashion & Luxury", "SaaS & Technology", "Healthcare & MedTech", "Professional Services"],
  },
  london: {
    name: "London",
    country: "United Kingdom",
    flag: "🇬🇧",
    tagline: "Europe's Premier Business Hub.",
    sub: "London-based and UK-wide brands trust us for sophisticated digital strategies that align with British buyer behaviour, Google UK rankings, and the competitive European landscape.",
    badge: "UK",
    stats: [["9M+", "Greater London Population"], ["£517B", "London GDP"], ["96%", "UK Internet Usage"], ["#3", "Global Financial Centre"]],
    services: [
      ["SEO Agency London", "Google.co.uk dominance for your target keywords.", "sol-seo"],
      ["PPC Agency London", "Google and Meta ads built around British buying patterns.", "sol-ads"],
      ["B2B Lead Generation UK", "Decision-maker targeting across London's financial and tech sectors.", "sol-leadgen"],
      ["Personal Branding London", "Executive authority building in the UK business community.", "sol-linkedin"],
    ],
    why: "London buyers are sophisticated and research-driven. They demand brand credibility before they engage. Our content strategies build topical authority that works for Google UK, while our paid campaigns are calibrated to British conversion benchmarks and GDPR-compliant targeting.",
    market: ["Google.co.uk ranking factors", "British consumer trust signals", "GDPR-compliant digital marketing", "UK financial & professional services regulation", "London's multicultural audience segments"],
    industries: ["Finance & Fintech", "Legal & Professional Services", "Real Estate", "Fashion & Retail", "Technology & SaaS", "Healthcare & Pharma"],
  },
  sydney: {
    name: "Sydney",
    country: "Australia",
    flag: "🇦🇺",
    tagline: "Australia's Digital Growth Capital.",
    sub: "Sydney brands competing in Australia's growing digital economy need SEO and paid media that understands local search behaviour, Google.com.au, and the unique Australian consumer mindset.",
    badge: "AUS",
    stats: [["5.3M+", "Greater Sydney Population"], ["96%", "Internet Penetration"], ["94%", "Google Market Share AU"], ["$450B+", "NSW Economy"]],
    services: [
      ["SEO Agency Sydney", "Google.com.au first-page rankings for high-intent Australian keywords.", "sol-seo"],
      ["Google Ads Sydney", "Australian audience targeting with verified ROAS.", "sol-ads"],
      ["Local SEO Sydney", "Near-me and suburb-level dominance across Greater Sydney.", "sol-localseo"],
      ["Social Media Sydney", "Instagram, LinkedIn and Facebook strategies for Australian audiences.", "sol-social"],
    ],
    why: "Australians are among the world's heaviest mobile internet users. Sydney's market is highly competitive in real estate, healthcare, and professional services. We build campaigns that match Australian search intent, leverage the trust signals Australian buyers value, and comply with ACCC marketing guidelines.",
    market: ["Google.com.au algorithm preferences", "Australian consumer privacy expectations", "Mobile-first browsing behaviour (AU)", "Sydney suburb-level local SEO", "ACCC digital marketing compliance"],
    industries: ["Real Estate & Property", "Healthcare & Allied Health", "Financial Services", "Tourism & Hospitality", "Education & Training", "Retail & E-Commerce"],
  },
  mumbai: {
    name: "Mumbai",
    country: "India",
    flag: "🇮🇳",
    tagline: "India's Financial Capital. Your Digital Frontier.",
    sub: "Mumbai is India's most lucrative consumer market. We help Mumbai-based businesses and Indian brands targeting global markets build digital authority, drive qualified traffic, and generate measurable growth.",
    badge: "IND",
    stats: [["20M+", "Greater Mumbai Population"], ["$310B+", "Mumbai GDP"], ["900M+", "Internet Users in India"], ["#1", "India's Financial Hub"]],
    services: [
      ["SEO Agency Mumbai", "Hindi and English SEO that captures India's fastest-growing search market.", "sol-seo"],
      ["Performance Marketing India", "Meta, Google, and YouTube campaigns calibrated for Indian CPL benchmarks.", "sol-ads"],
      ["Lead Generation Mumbai", "B2B pipelines targeting Mumbai's financial and industrial sectors.", "sol-leadgen"],
      ["Website Design Mumbai", "Conversion-first websites built for India's mobile-first audience.", "sol-web"],
    ],
    why: "Mumbai is where Indian business happens — and where the competition is fiercest. With over 900 million internet users in India and a rapidly maturing digital ad market, you need hyper-local strategies that speak to India's diverse buyer segments. We are based here. We know this market intimately.",
    market: ["Hindi & regional language SEO", "India's mobile-first user behaviour", "Indian UPI & payment ecosystem", "TRAI digital marketing compliance", "Tier-1 vs Tier-2 city targeting differences"],
    industries: ["Financial Services & BFSI", "Real Estate", "E-Commerce & D2C", "Healthcare & Pharma", "Education & EdTech", "Manufacturing & Export"],
  },
  riyadh: {
    name: "Riyadh",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    tagline: "The Kingdom's Digital Economy is Open.",
    sub: "Saudi Arabia's Vision 2030 is reshaping its economy and creating a massive digital opportunity. We help brands establish authority, generate leads, and grow in the Kingdom's capital market.",
    badge: "KSA",
    stats: [["7.7M+", "Greater Riyadh Population"], ["$400B+", "Saudi GDP"], ["99%", "Internet Penetration KSA"], ["70%", "Population Under 35"]],
    services: [
      ["SEO Agency Riyadh", "Google.com.sa rankings in Arabic and English for Saudi search.", "sol-seo"],
      ["Digital Marketing Saudi Arabia", "Vision 2030-aligned growth strategies for Saudi brands.", "sol-consulting"],
      ["Google Ads Saudi Arabia", "Saudi-specific audience targeting with Arabic-language creatives.", "sol-ads"],
      ["Social Media Saudi Arabia", "Snapchat, Instagram, and Twitter strategies for the Kingdom's young audience.", "sol-social"],
    ],
    why: "Saudi Arabia has one of the world's youngest and most digitally active populations. Vision 2030 is opening sectors that were previously closed to private enterprise. Brands that establish digital authority now will own the market as the economy diversifies. Our Arabic-first strategies are built for the Saudi buyer.",
    market: ["Arabic-first SEO and content strategy", "Vision 2030 priority sectors", "Saudi social media platform preferences (Snapchat)", "Halal marketing compliance", "CITC digital advertising regulations"],
    industries: ["Real Estate & Construction", "Retail & E-Commerce", "Tourism & Entertainment", "Healthcare & Pharma", "Education", "Technology & IT"],
  },
  johannesburg: {
    name: "Johannesburg",
    country: "South Africa",
    flag: "🇿🇦",
    tagline: "Africa's Economic Powerhouse.",
    sub: "Johannesburg is Sub-Saharan Africa's largest economy. We help Joburg-based brands and international businesses entering the African market build a digital presence that drives real commercial results.",
    badge: "ZA",
    stats: [["5.6M+", "Greater Joburg Population"], ["$100B+", "Joburg Metropolitan GDP"], ["72%", "SA Internet Usage"], ["#1", "Africa's Largest Economy"]],
    services: [
      ["SEO Agency Johannesburg", "Google.co.za first-page rankings for South African search queries.", "sol-seo"],
      ["Digital Marketing South Africa", "Data-driven growth strategies for South Africa's unique market.", "sol-consulting"],
      ["Google Ads South Africa", "Rand-optimised PPC campaigns for South African buyers.", "sol-ads"],
      ["Social Media South Africa", "Facebook, Instagram, and LinkedIn for SA's diverse audience.", "sol-social"],
    ],
    why: "South Africa presents a unique digital opportunity: a sophisticated, English-speaking consumer base with high mobile internet usage but relatively lower competition compared to Western markets. Brands that invest in SEO and paid media now can own categories before the market fully matures.",
    market: ["South African consumer trust signals", "POPIA data protection compliance", "Multi-language targeting (English, Zulu, Xhosa)", "SA mobile-first internet usage", "Rand-denominated ad budget optimization"],
    industries: ["Mining & Resources", "Financial Services", "Retail & FMCG", "Healthcare", "Real Estate & Property", "Technology"],
  },
} as const;
