import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'caseStudy',
  title: 'Case Study',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'client',
      title: 'Client',
      type: 'string',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'industry',
      title: 'Industry',
      type: 'string',
      options: {
        list: [
          { title: 'SaaS', value: 'SaaS' },
          { title: 'Healthcare & Medical', value: 'Healthcare & Medical' },
          { title: 'Architecture & Design', value: 'Architecture & Design' },
          { title: 'Technology & AI', value: 'Technology & AI' },
          { title: 'Real Estate & Development', value: 'Real Estate & Development' },
          { title: 'Restaurants & Cafes', value: 'Restaurants & Cafes' },
          { title: 'Fashion & Apparel', value: 'Fashion & Apparel' },
          { title: 'B2B Services', value: 'B2B Services' },
          { title: 'B2C Brands', value: 'B2C Brands' },
        ],
      },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'services',
      title: 'Services',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
        list: [
          { title: 'SEO', value: 'SEO' },
          { title: 'AEO', value: 'AEO' },
          { title: 'GEO', value: 'GEO' },
          { title: 'Web Development', value: 'Web Development' },
          { title: 'Local SEO', value: 'Local SEO' },
          { title: 'Reputation Management', value: 'Reputation Management' },
          { title: 'Image Engine Optimization', value: 'Image Engine Optimization' },
          { title: 'Lead Generation', value: 'Lead Generation' },
          { title: 'Content Strategy', value: 'Content Strategy' },
          { title: 'Social Media', value: 'Social Media' },
        ],
      },
    }),
    defineField({
      name: 'summary',
      title: 'Summary (for meta + cards)',
      type: 'text',
      rows: 2,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'overview',
      title: 'Overview (hero paragraph)',
      type: 'text',
      rows: 3,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'challenge',
      title: 'Challenge',
      type: 'text',
      rows: 4,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'solution',
      title: 'Solution',
      type: 'text',
      rows: 4,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'strategy',
      title: 'Strategy',
      type: 'text',
      rows: 4,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'execution',
      title: 'Execution Steps',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Each item is one execution step, e.g. "Conducted a 3-week keyword research sprint..."',
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: 'outcomes',
      title: 'Outcomes',
      type: 'text',
      rows: 4,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'conclusion',
      title: 'Conclusion',
      type: 'text',
      rows: 4,
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'results',
      title: 'Key Results',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'e.g. "+312% organic search traffic in 90 days"',
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: 'image',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'date',
      title: 'Date',
      type: 'date',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'client', media: 'image' },
  },
})
